### PR TITLE
Added gitlab, updated icons

### PR DESCRIPTION
**Pull request by eightam**
Hi, I've included GitLab support - and added the icons and translations for it.
Additionally, I think having to use only one icon for private github repos and the readme is a little more elegant. I've already included the matching gitlab icon so it can be used as soon as github-updater supports it.

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
I confirm that the portuguese translation is ok :+1:

**Comment by szepeviktor** [comment]
Thank you for the blue locks.

**Comment by szepeviktor** [comment]
> I've already included the matching gitlab icon so it can be used as soon as github-updater supports it.

Seems like it does: https://github.com/afragen/github-updater/search?utf8=%E2%9C%93&q=gitlab

**Comment by szepeviktor** [comment]
@eightam Do you have an open-source GitLab example plugin? Maybe one that is on WP.org also.

**Comment by eightam** [comment]
Oh sorry, misunderstanding: Sure it already supports gitlab, that is why I made it ...
But it does not support the included token yet - so the gitlab blue lock icon is not yet used, but already in the commit ...

**Comment by szepeviktor** [comment]
I think it does: "Enter GitLab Private Token for private GitLab repositories."
https://github.com/afragen/github-updater/search?utf8=%E2%9C%93&q=GitLab+Token&type=Code

**Comment by eightam** [comment]
True, but not preset in the plugin/theme file I guess.

**Comment by szepeviktor** [comment]
See here: https://github.com/afragen/github-updater/blob/b9cde96c3ff320871122ddbe5adef8a7b9057872/README.md#gitlab-ceenterprise-support

**Comment by szepeviktor** [comment]
I see! You are missing it from this screen: `/options-general.php?page=github-updater&tab=github_updater_settings`
I think that is only for updates. GitLab token should be in the plugin's header.

**Pull request merged**
